### ISSUE TITLE
addRegionMonitoringSubscriber

### ISSUE THREAD

**Issue by bogdantmm92** [foursquare/FSQLocationBroker#3] opened 2015-06-30 11:27 UTC
I need to register a monitor subscriber when the app starts in order to get notified when the user enters a specific geofence. The problem is that I don't have( and don't want imediate) access to subscriber's regions(the regions are not hardcoded). In that case, when I call "addRegionMonitoringSubscriber", the library will think that all my geofences are unmonitored and will remove them. Am I missing something?

**Comment by bdorfman** [comment] 2015-06-30 19:46
Ah, this looks like it might be a regression in our code, I am sorry. It is supposed to re-pair geofences with subscribers on app startup based on `subscriberIdentifier`, but it looks like it is too aggressively clearing out monitored regions. I will work on a fix, sorry about this.

**Comment by bogdantmm92** [comment] 2015-07-01 05:33
No problem @bdorfman . Thanks for looking into this. Do you have an et? I could try to fix it if not.

**Comment by bdorfman** [comment] 2015-07-01 06:49
I have a fix already written up. Just want to run it by some coworkers and do a bit more testing before pushing. Hopefully have something up here for you tomorrow.

**Comment by bogdantmm92** [comment] 2015-07-01 07:09
Great news, Thanks!

**Comment by bdorfman** [comment] 2015-07-01 19:57
I have pushed a substantial rewrite of how the broker deals with region subscribers. It should now properly reconnect your subscribers to any regions they were monitoring on a previous app launch. A thorough list of changes and fixes is in the commit description.

Please update to latest master and let me know if this solves your problem. If so I will bump the version number and push out a new release.

**Comment by bogdantmm92** [comment] 2015-07-03 11:44
It works, thanks!
The only "problem" is that 
```
@property (nonatomic, readonly) NSSet *monitoredRegions;
```
 is immutable, so it's not very optimum to create a new set when adding a new region from
```
- (void)addMonitoredRegion:(CLRegion *)region;  
```
Especially when the app is in background and you listen to 10-20 geofences. What do you think?
I'm not very used to objc, so again I may miss something.

**Comment by bdorfman** [comment] 2015-07-03 16:42
Glad the issue is fixed for you!

Generally immutable collections are preferable to mutable ones for thread safety regions. If you are mutating the set while the broker is trying to read out from it on another thread, that will cause a crash. `self.monitoredRegions = [self.monitoredRegions setByAddingObject:newRegion]` shouldn't have any noticeable difference in performance.

Note that, since the protocol specifies a readonly property, you can theoretically provide any subclass of NSSet (such as NSMutableSet) as the actual property on your class and it should fulfill the conformance requirement. However I don't recommend this for the reasons given above.

Closing this issue for now, but if you have any other questions feel free to reach out to me. Always happy to help.

**Closed by bdorfman** 2015-07-03 16:42 UTC

**Comment by bogdantmm92** [comment] 2015-07-06 08:36
Could you please publish a new release? I want to be able to get it from npm.

**Comment by bdorfman** [comment] 2015-07-06 17:55
Yes, I'll do that today.

**Comment by bdorfman** [comment] 2015-07-06 20:27
Version bumped and new podspec has been pushed to cocoapods trunk.

**Comment by bogdantmm92** [comment] 2015-07-09 17:57
I need to do the following things:
- change the position of a region with the same id
- force update the regions for a specific subscriber

@bdorfman I think that the only way to remove a region from a RegionMonitoringSubscriber is by removing the RegionMonitoringSubscriber itself.

**Comment by bdorfman** [comment] 2015-07-14 18:54
If you just set a new NSSet to your monitoredRegions property that has the region you want to remove, removed it should update CLLocationManager for you if your property is KVO compliant. Otherwise you need to manually call refreshRegionMonitoringSubscribers after you make a change.

Regions are uniqued based on identifier, because CLLocationManager does not guarantee it will return you the same region objects you provided when you ask for them, only that the identifiers will be the same. If you change the bounds of the region you should change the identifier as well.

**Comment by bogdantmm92** [comment] 2015-07-20 12:22
From what I've seen, refreshRegionMonitoringSubscribers won't remove unmonitored regions. The region would be removed only if I call refreshRegionMonitoringSubscribersRemovingSubscriberWithIdentifer: identifier shouldRemoveAllUnmonitoredRegions: false (or true), but this method is private .

I need to modify the same region because I'm tracking user's location using geofences(it's more battery efficient). When exit events gets triggered, I fetch the new location & move the region's center in that location.

**Comment by bdorfman** [comment] 2015-07-20 17:35
I am not sure exactly what you are doing, but it works fine for me. If I set my regions to be, for example, regions with identifiers "SubscriberID+Test1" and "SubscriberID+Test2", and then later set them again to be just "SubscriberID+Test1", the region identified as "SubscriberID+Test2" gets removed properly for me.

CLLocationManager has no mechanism to change currently monitored regions. You have to remove the old one and then add a new one.
